@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "UserPrefs Storage" #F4F6F6{
Class JsonUserPrefsStorage
}

package "Client and pet storage" #F4F6F6{
Class ClientPetData
Class JsonClientPetStorage
Class JsonSerializableClientPetData
Class JsonAdaptedClient
Class JsonAdaptedPet
Class JsonAdaptedTag
}

package "Appointment storage" #F4F6F6{
Class "<<interface>>\nAppointmentStorage" as AppointmentStorage
Class JsonAppointmentBookStorage
Class JsonSerializableAppointmentBook
Class JsonAdaptedAppointment
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
Storage .up.|> AppointmentStorage
JsonAppointmentBookStorage .up.|> AppointmentStorage
StorageManager -down-> "1" JsonUserPrefsStorage
StorageManager -down-> "1" JsonClientPetStorage

JsonClientPetStorage ..> JsonSerializableClientPetData
JsonClientPetStorage ..> ClientPetData
StorageManager --> JsonAppointmentBookStorage
JsonAppointmentBookStorage ..> JsonSerializableAppointmentBook
JsonSerializableAppointmentBook --> "*" JsonAdaptedAppointment
JsonSerializableClientPetData --> "*" JsonAdaptedClient
JsonSerializableClientPetData --> "*" JsonAdaptedPet
JsonAdaptedClient --> "*" JsonAdaptedTag

@enduml
